name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-scc-frontend:
    name: Build SCC Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/scc-website:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/scc-website:latest
      
          